### ISSUE TITLE
Infinity scroll

### ISSUE THREAD

**Issue by bugrevealingbme** [yousifk/marquee_widget#10]
Please add infinity scroll feature

**Comment by yousifk** [comment]
What's your meaning about the infinity scroll?

**Comment by aytunch** [comment]
He means, instead of going back and forward, It can always go forward and when the content is finished, the same content will show
 a b c d e_____a b c d e_____a b c d e_____a b c d e_____a b c d e..........to infinity <---------
----------------------- [________]
-----------------------visible widget
